# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: "%env(APP_SECRET)%"
  annotations: false
  http_method_override: false
  handle_all_throwables: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: null
    cookie_secure: false # Désactivé pour HTTP
    cookie_samesite: "lax"
    cookie_lifetime: 0

  #esi: true
  #fragments: true
  php_errors:
    log: true

  messenger:
    # Uncomment this (and the failed transport below) to send sync messages
    # sync: 'sync://'

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async: "doctrine://default"

    routing:
      # Pour envoyer les emails immédiatement, commentez ou modifiez cette ligne
      #Symfony\Component\Mailer\Messenger\SendEmailMessage: async
when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
